# 6 different services to be defined
services:
  server:
    # adapted for prod deployment strategy
    # image: nginx:stable-alpine    
    # below 3 lines will fail as the context needs to see src/ and nginx/
    # build:
    #   context: ./dockerfiles
    #   dockerfile: nginx.dockerfile    
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro     # ro: container should never change the conf.
    depends_on:
      - phpapp
      - mysql

  phpapp:
    # adjusted below for the same purpose mentioned for "server".
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    # The prod deployment strategy is to eliminate the need of defining bind mounts 
      # in app level (phpapp).
    volumes:
      - ./src:/var/www/html:delegate    # delegate: optimization for writing to host in batches
                                        # ro: is not an option here as e.g. view files needs to be generated which needs
                                        # be worked on the host
      # port: 3000:9000       # as we have container-container communication, no mapping needed here.
                              # this nginx line will suffice -> phpapp:9000

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:         # same dockerfile as phpapp is fine as it needs php
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]          # overriding/adding the setting (ENTRYPOINT) inside dockerfile
  npm:
    image: node:20
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
