# 6 different services to be defined
services:
  server:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro     # ro: container should never change the conf.
    depends_on:
      - phpapp
      - mysql

  phpapp:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegate    # delegate: optimization for writing to host in batches
                                        # ro: is not an option here as e.g. view files needs to be generated which needs
                                        # be worked on the host
      # port: 3000:9000       # as we have container-container communication, no mapping needed here.
                              # this nginx line will suffice -> phpapp:9000

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # artisan:
  # npm:
